version : "3.3"
services :
  web :
     image: "bhupendradixit/notes-app:latest"
     ports :
         - "8000:8001"


  services:
  web:
    build: .
    ports:
      - "8080:8000" # Change host port to 8080
       
